# Default values for ClickHouse-operator

operator:
  image: dbkernel/clickhouse-operator:0.14.0
  imagePullPolicy: IfNotPresent
metrics_operator:
  image: dbkernel/clickhouse-metrics-operator:0.14.0
  imagePullPolicy: IfNotPresent
