apiVersion: v2
name: mysql-ha
description: High Availability MySQL Cluster, Open Source.
home: https://github.com/dbkernel/helm-charts/charts/mysql-ha

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "5.7.34"

kubeVersion: ">=1.17.0-0"
sources:
  - https://github.com/dbkernel/helm-charts/charts/mysql-ha
keywords:
  - DBKernel
  - MySQL HA
  - database
  - kubernetes

maintainers:
  - email: wenshuang_lu@163.com
    name: DBKernel
    url: https://dbkernel.github.io/

icon: https://dbkernel-1306518848.cos.ap-beijing.myqcloud.com/logos/logo-dbkernel-green.svg
annotations:
  category: Database
